// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx53CzG8OXh9r8DzmrGur7xlHVtWrjd4Y',
    appId: '1:880790845788:web:74f99d0e79c52b9cb4e999',
    messagingSenderId: '880790845788',
    projectId: 'golemons-ee306',
    authDomain: 'golemons-ee306.firebaseapp.com',
    storageBucket: 'golemons-ee306.firebasestorage.app',
    measurementId: 'G-1XS2K6T5XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKn62T5HCM7JghmmqyocKm9YPffzlLHNg',
    appId: '1:880790845788:android:271cbc33f3aebeabb4e999',
    messagingSenderId: '880790845788',
    projectId: 'golemons-ee306',
    storageBucket: 'golemons-ee306.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHjb0TJASH-k72a_FIngSgEsHH42rCE5k',
    appId: '1:880790845788:ios:4044319c486f5675b4e999',
    messagingSenderId: '880790845788',
    projectId: 'golemons-ee306',
    storageBucket: 'golemons-ee306.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHjb0TJASH-k72a_FIngSgEsHH42rCE5k',
    appId: '1:880790845788:ios:4044319c486f5675b4e999',
    messagingSenderId: '880790845788',
    projectId: 'golemons-ee306',
    storageBucket: 'golemons-ee306.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx53CzG8OXh9r8DzmrGur7xlHVtWrjd4Y',
    appId: '1:880790845788:web:8875d993d738405bb4e999',
    messagingSenderId: '880790845788',
    projectId: 'golemons-ee306',
    authDomain: 'golemons-ee306.firebaseapp.com',
    storageBucket: 'golemons-ee306.firebasestorage.app',
    measurementId: 'G-Z3H49S3PSQ',
  );
}
